JUMP_VELOCITY = -4.25
FROM_WALL_JUMP_VERTICAL_VELOCITY = -4.25
LEFT_VELOCITY = -3
RIGHT_VELOCITY = 3
DEFAULT_ACCELARATION = 0.25
DEFAULT_MAX_FALL_SPEED = 5
ON_WALL_ACCELARATION = 0.1
ON_WALL_MAX_FALL_SPEED = 2

CANVAS_SCALE = 3

IS_DEBUG = false