JUMP_VELOCITY = -4.25
FROM_WALL_JUMP_VERTICAL_VELOCITY = -4.25
LEFT_VELOCITY = -3
RIGHT_VELOCITY = 3
DEFAULT_ACCELARATION = 0.25
DEFAULT_MAX_FALL_SPEED = 5
ON_WALL_ACCELARATION = 0.1
ON_WALL_MAX_FALL_SPEED = 2

CANVAS_SCALE = 4

COIN_IMAGE_SRC = './src/maps/additionalAssets/coin.png'
COIN_IMAGE_SIZE = 32
COIN_HITBOX_SIZE = 16

STATS_BACKGROUND_SRC = './src/maps/additionalAssets/statsBackground.png'
STATS_TEXT_FONT = '16px Arial Helvetica sans-serif'
STATS_TEXT_COLOR = 'rgb(254, 183, 29)'

IS_DEBUG = false
